### ISSUE TITLE
AOT support? 

### ISSUE THREAD

**Issue by ArielGueta** [johannesjo/generator-angular2-lib#1]
Hey, I am wondering about AOT compatibility of the library?

**Comment by johannesjo** [comment]
Thanks for your question. It should work. You can check out https://github.com/johannesjo/angular2-promise-buttons which is based on this generator and works absolutely fine with aot.

**Comment by ArielGueta** [comment]
I can't see any` *.metadata.json` files that are being generated for AOT or am I missing something?

**Comment by johannesjo** [comment]
With npm run build?

**Comment by ArielGueta** [comment]
I will test this and let you know

**Comment by johannesjo** [comment]
Thank you very much. I'm currently not at home, but if it  doesn't work for some reason, I'll fix it later.
