### ISSUE TITLE
Cannot find exported modules/components

### ISSUE THREAD

**Issue by 0xMatt** [johannesjo/generator-angular2-lib#2]
This may definitely be a user error and if so I can try my best to provide additional details, but I still want to display my issue in case someone may have any tips on how to resolve it.

For some reason, my demo application will not compile, it's not able to find any of the exported components by the actual source of the library. I'm getting really strange errors like this:

    ERROR in /home/matthew/git/ngx-admin/demo/src/$$_gendir/src/ui/navbar/navbar.component.ngfactory.ts (10,21): Cannot find module './navbar.component'.

    ERROR in /home/matthew/git/ngx-admin/demo/src/$$_gendir/src/ui/sidebar/sidebar.component.ngfactory.ts (14,21): Cannot find module './sidebar.component'.

    ERROR in /home/matthew/git/ngx-admin/demo/src/$$_gendir/src/ui/sidebar/sidebar.component.ngfactory.ts (15,21): Cannot find module '../../admin/services/auth.service'.

As you can see, some components are not able to find themselves, and some services cannot be found when I have to back out of the current directory.

For the auth service not being able to be located, I was not able to fix that without breaking the actual demo. I had exported the auth service in the other module it was included in ,and changed the import path from `../../admin/services/auth.service'` to `../../` which did not work.

The _only_ module throwing these errors are this UI module, it is exported by the core bundle with all components exported. No other modules display errors like this.

[Here's](http://i.imgur.com/YkOWFcz.png) a screenshot giving a general overview of my project structure. I know it's a shot in the dark posting my issue here and I'll probably just need to rebuild everything piece by piece down the road, but figured I'd ask for help before I did so.

**Comment by 0xMatt** [comment]
This issue was a module in `demo/src/` was including a module in `src/` and not `component-symlink`

**Comment by johannesjo** [comment]
Thanks for reporting and reporting back. Glad that it works for you now.
