### ISSUE TITLE
Future of this lib?

### ISSUE THREAD

**Issue by 0xMatt** [johannesjo/generator-angular2-lib#3]
No updates in 3mo, this is a bit concerning since I've built a few libs with this library and found it to be the best out of all the others I've used out there. I just want to know if you have any plans on maintaining and improving this generator so I can plan what I'll be doing in the future as far as lib development goes. Thanks!

**Comment by johannesjo** [comment]
Hey there! I definitely plan on keeping this up to date whenever I can! Currently I'm not working on any module for ng2 and nobody else reported any issues so there hasn't been the need for me to update this. If you encounter some issue or some missing feature always feel free to open an issue about it and hopefully we'll find a solution for this.

**Comment by johannesjo** [comment]
I'm curious! What have you been using this generator for so far? :)

**Comment by 0xMatt** [comment]
Heh, seems you just gave it a star. So far, that is the only open source lib I've made with this, but have it used for several libraries used internally at work. 

As far as issues goes, I think they have something to do with the symlink, as sometimes when I run tests after making changes I get weird behavior, like a vague error but it goes away after the second run. However that wasn't really something I could articulate well enough to report, but that's pretty much it. That's mostly why I like this library, not really any issues, very easy to use, so I commend you for doing such a good job. My concern was just that it stays updated with the latest dependencies and whatnot. 

Thanks for the quick reply!

**Comment by johannesjo** [comment]
Your lib looks promising! Looking forward to give it a try the next time I need to use OAuth.

I totally understand your concerns. There just too many abandoned libs out there. I can't promise to always be able to have time to fix an issue, but I promise that I'll try to at least respond.

**Comment by 0xMatt** [comment]
Regarding my lib, thank you!

As far as what we've discussed, that's good peace of mind to know that this lib isn't abandoned and you'll update it when you find necessary. Thanks for the info and transparency and keep up the good work!
